---

secrets:
  radarr-api:
    file: ./secrets/radarr-api.secret
  sonarr-api:
    file: ./secrets/sonarr-api.secret

services:
  sonarr:
    # See more: https://docs.linuxserver.io/images/docker-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes:
      - sonarr:/config
      - data:/media
    healthcheck:
      test: curl -f http://localhost:8989/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      traefik:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true
      

  radarr:
    # See more: https://docs.linuxserver.io/images/docker-radarr
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes:
      - radarr:/config
      - data:/media
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      traefik:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true

  prowlarr:
    # See more: https://docs.linuxserver.io/images/docker-prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes: 
      - prowlarr:/config
      - data:/media
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      traefik:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true

  unpackerr:
    # See more: https://unpackerr.zip/docs/install/compose
    image: golift/unpackerr
    container_name: unpackerr
    restart: always
    secrets:
      - radarr-api
      - sonarr-api
    env_file: ./env/arr.env
    volumes:
      - data:/media
      - unpackerr:/config
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  data: # Sonarr, Radarr, Prowlarr, and Unpackerr data mount
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${NFS_VOLUME}/data"

  sonarr: # Sonarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${NFS_VOLUME}/docker_data/sonarr"

  radarr: # Radarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${NFS_VOLUME}/docker_data/radarr"

  prowlarr: # Prowlarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${NFS_VOLUME}/docker_data/prowlarr"

  unpackerr: # unPackerr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${NFS_VOLUME}/docker_data/unpackerr"