---

services:

  watchtower:
    # See more: https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    container_name: watchtower
    env_file: 
      - ./env/watchtower.env
      - ./env/nfs.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

include:
  - bittorrent-compose.yml
  - arr-compose.yml
#  - plex-compose.yml
#  - jellyfin-compose.yml

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

# No volumes needed for watchtower