---

secrets:
  openvpn_user:
    file: ./secrets/openvpn_user.secret
  openvpn_password:
    file: ./secrets/openvpn_password.secret

services:

  gluetun:
    # See more: https://github.com/qdm12/gluetun-wiki
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    secrets:
      - openvpn_user
      - openvpn_password
    env_file: 
      - ./env/gluetun.env
      - ./env/nfs.env
    volumes:
      - gluetun:/gluetun

  watchtower:
    # See more: https://github.com/containrrr/watchtower
    image: containrrr/watchtower
    container_name: watchtower
    env_file: 
      - ./env/watchtower.env
      - ./env/nfs.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

include:
  - bittorrent-compose.yml
  - arr-compose.yml
#  - plex-compose.yml
#  - jellyfin-compose.yml

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  gluetun: # Gluetun app data.
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${MEDIA_PATH}/docker_data/gluetun"